---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.38.125
vector:
  hosts:
    vector-01:
      ansible_host: 51.250.38.125
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.38.125
